### ISSUE TITLE
相同行会导致栈溢出🐛

### ISSUE THREAD

**Issue by xiaoxiao992** [antvis/S2#1427]
### 透视表相同行会导致栈溢出

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |  1.19.0        |
| @antv/s2-react |    ^1.17.0      |
| @antv/s2-vue   |          |

### Sheet Type

- [ ] PivotSheet

### 🖋 Description

透视表如果选择两个相同的字段进入行，就会导致页面奔溃

### ⌨️ Code Snapshots

Maximum call stack size exceeded
    at baseGet (index.js:14091:1)
    at get (index.js:14129:1)
    at _loop_2 (index.js:47447:1)
    at PivotDataSet.getDimensionValues (index.js:47467:1)
    at buildGridHierarchy (index.js:31711:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
baseGet @ index.js:14091
get @ index.js:14129
_loop_2 @ index.js:47447
PivotDataSet.getDimensionValues @ index.js:47467
buildGridHierarchy @ index.js:31711
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
buildGridHierarchy @ index.js:31762
generateHeaderNodes @ index.js:31877
显示另外 170 个框架
index.js:20538 Uncaught RangeError: Maximum call stack size exceeded
    at includes (index.js:20538:1)
    at PivotDataSet.getDimensionValues (index.js:47435:1)
    at buildGridHierarchy (index.js:31711:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)
    at buildGridHierarchy (index.js:31762:1)
    at generateHeaderNodes (index.js:31877:1)

### 🔗 Reproduce Link
https://codesandbox.io/s/nifty-pare-32hygi

### 🤔 Steps to Reproduce
  fields: {
    rows: ["province", "city", 'city'], // rows 相同的city就直接报错
    columns: ["type"], // 列相同，就不展示列
    values: ["price"]
  },

### 😊 Expected Behavior
期望可以支持相同项

### 😅 Current Behavior
当前栈溢出

**Comment by lijinke666** [comment]
配置两个相同的字段的目的是？

**Comment by lijinke666** [comment]
dataCfg 的 fields 不能配置相同的字段, 我们做一下容错, 并不是 bug

**Comment by xiaoxiao992** [comment]
感谢，现在发现只要fields配置相同，会遇到很多问题，透视表里面相同的rows 。columns， values 都会出现不同程度的严重问题，相同的指标如果去隐藏，会导致页面无数据，明细表里面相同的columns 会导致隐藏列，隐藏的回显图标不见了

**Comment by lijinke666** [comment]
> 感谢，现在发现只要fields配置相同，会遇到很多问题，透视表里面相同的rows 。columns， values 都会出现不同程度的严重问题，相同的指标如果去隐藏，会导致页面无数据，明细表里面相同的columns 会导致隐藏列，隐藏的回显图标不见了

恩, fields 需要有唯一性, 不支持相同的字段, 我们内部做一下去重处理, 并给出提示
